apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-ctr
        image: mongo:3.3
        command: ["mongod"]
        args: ["--rest", "--httpinterface"]
