apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    type: db
    vendor: Mongo Labs
spec:
  containers:
  - name: db
    image: mongo
    command: ["mongod"]
    args: ["--rest", "--httpinterface"]
