apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: db-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-ctr
        image: mongo
        command: ["mongod"]
        args: ["--rest", "--httpinterface"]
