apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-demo-2-api-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      stack: go-demo-2
      type: api
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        stack: go-demo-2
        type: api
    spec:
      containers:
      - name: go-demo-2-api-ctr
        image: vfarcic/go-demo-2:1
        env:
        - name: DB
          value: go-demo-2-db-svc
