apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-api-svc
  labels:
    stack: go-demo-2
    type: api
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    stack: go-demo-2
    type: api