apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-demo-2-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: go-demo-2
      type: db
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        stack: go-demo-2
        type: db
    spec:
      containers:
      - name: go-demo-2-db-ctr
        image: mongo:3.3
