apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-db-svc
  labels:
    stack: go-demo-2
    type: db
spec:
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
  selector:
    stack: go-demo-2
    type: db