apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 3000

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      type: monitor
      service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: monitor
        service: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:4.6.3
        env:
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:/grafana"
        - name: GF_SERVER_DOMAIN
          value: 192.168.99.100
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-vol
      volumes:
      - emptyDir: {}
        name: grafana-vol
        

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
  selector:
    type: monitor
    service: grafana
