apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      labels:
        type: db
        vendor: MongoLabs
    spec:
      containers:
      - name: db
        image: mongo
        command: ["mongod"]
        args: ["--rest", "--httpinterface"]
