---
# Source: cluster-autoscaler/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.12.2
    heritage: Tiller
    release: aws-cluster-autoscaler
  name: aws-cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: aws-cluster-autoscaler
      release: aws-cluster-autoscaler
  maxUnavailable: 1
  # minAvailable: 2
  