---
# Source: cluster-autoscaler/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.14.2
    heritage: Tiller
    release: aws-cluster-autoscaler
  name: aws-cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: aws-cluster-autoscaler
    namespace: kube-system