---
# Source: cluster-autoscaler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.14.2
    heritage: Tiller
    release: aws-cluster-autoscaler
  name: aws-cluster-autoscaler