apiVersion: v1
kind: Namespace
metadata:
  name: test1

---

apiVersion: v1
kind: Namespace
metadata:
  name: test2

---

apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test1
spec:
  serviceAccountName: pods-all
  containers:
  - name: test
    image: alpine:3.5
    command: ["sleep"]
    args: ["100000"]
