apiVersion: v1
kind: Namespace
metadata:
  name: jenkins

---

apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins
  namespace: jenkins
spec:
  limits:
  - default:
      memory: 2Gi
      cpu: 2
    defaultRequest:
      memory: 1Gi
      cpu: 1
    max:
      memory: 4Gi
      cpu: 3
    min:
      memory: 500Mi
      cpu: 0.5
    type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: jenkins
  namespace: jenkins
spec:
  hard:
    requests.cpu: 8
    requests.memory: 32Gi
    limits.cpu: 10
    limits.memory: 40Gi
    pods: 20