Master:
  ImageTag: "2.129-alpine"
  Cpu: "500m"
  Memory: "500Mi"
  ServiceType: ClusterIP
  ServiceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  InstallPlugins:
  - blueocean:1.6.1
  - credentials:2.1.17
  - ec2:1.39
  - git:3.9.1
  - git-client:2.7.2
  - github:1.29.2
  - kubernetes:1.9.2
  - pipeline-utility-steps:2.1.0
  - script-security:1.44
  - slack:2.3
  - thinBackup:1.9
  - workflow-aggregator:2.5
  - ssh-slaves:1.26
  - ssh-agent:1.15
  - jdk-tool:1.1
  - command-launcher:1.2
  - github-oauth:0.29
  - google-compute-engine:1.0.4
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
  HostName: jenkins.acme.com
rbac:
  install: true
  # roleBindingKind: RoleBinding
